export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG'

export const CHANGE_CURRENT_SONG_INDEX = 'CHANGE_CURRENT_SONG_INDEX'
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST'

export const CHANGE_PLAY_SEQUENCE = 'CHANGE_PLAY_SEQUENCE'

export const CHANGE_FIRST_LOAD = 'CHANGE_FIRST_LOAD'