export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG'

export const CHANGE_CURRENT_SONG_INDEX = 'CHANGE_CURRENT_SONG_INDEX'
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST'

export const CHANGE_PLAY_SEQUENCE = 'CHANGE_PLAY_SEQUENCE'

export const CHANGE_FIRST_LOAD = 'CHANGE_FIRST_LOAD'

export const CHANGE_LYRIC_LIST = 'CHANGE_LYRIC_LIST'
export const CHANGE_CURRENT_LYRIC_INDEX = 'CHANGE_CURRENT_LYRIC_INDEX'

export const CHANGE_ADD_SONG_DETAIL = 'CHANGE_ADD_SONG_DETAIL'
export const CHANGE_PLAY_LIST_COUNT = 'CHANGE_PLAY_LIST_COUNT'

export const CHANGE_HOT_COMMENT = 'CHANGE_HOT_COMMENT'
export const CHANGE_CURRENT_TOTAL = 'CHANGE_CURRENT_TOTAL'