export const CHANGE_TOP_BANNER = 'CHANGE_TOP_BANNER'
export const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND'
export const CHANGE_NEW_ALBUMS = 'CHANGE_NEW_ALBUMS'

export const CHANGE_UP_RAKING = 'CHANGE_UP_RAKING'
export const CHANGE_NEW_RAKING = 'CHANGE_NEW_RAKING'
export const CHANGE_ORIGIN_RAKING = 'CHANGE_ORIGIN_RAKING'